#!/bin/bash

java -cp "/Users/moxley/Dropbox/Programming/phys_world/sandbox/lwjgl-2.9.1.jar:/Users/moxley/lib/clojure.jar:/Users/moxley/lib/slick/lib/slick.jar:/Users/moxley/Dropbox/Programming/phys_world/lib/oskar_util.jar:src:." \
  -Djava.library.path=/Users/moxley/Dropbox/Programming/phys_world/sandbox/native/macosx/x86_64/ \
  clojure.main \
  --main phys-world.core
