#!/bin/bash

java -cp "/Users/moxley/Dropbox/Programming/try_lwjgl/sandbox/lwjgl-2.9.1.jar:/Users/moxley/lib/clojure.jar:/Users/moxley/lib/slick.jar:src:." \
  -Djava.library.path=/Users/moxley/Dropbox/Programming/try_lwjgl/sandbox/native/macosx/x86_64/ \
  clojure.main \
  --main try-lwjgl.core

